# -*- coding: utf-8 -*-
"""Projet_BI_Nettoyage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VUE5snpGNbrKp_r_1qqLxAOMj8bQabMR

##Importation des fichiers
"""

import pandas as pd
import numpy as np

"""##EXTRACTION"""

from google.colab import drive
drive.mount('/content/drive')

chemin_fichier = '/content/drive/MyDrive/data_intoxication.csv'

# Chargement du fichier dans un DataFrame Pandas
df = pd.read_csv(chemin_fichier)

# Affichage des premières lignes pour vérifier l'importation
display(df.head())

"""##Verification des doublons"""

def check_duplicates(df, name):
    duplicates = df.duplicated().sum()
    print(f'Doublons dans {name} : {duplicates}')

check_duplicates(df, "data_intoxication")

"""##Verifications des valeurs manquantes"""

def check_missing_values(df, name):
    missing_values = df.isnull().sum()
    total_values = df.shape[0]
    missing_percentage = (missing_values / total_values) * 100
    print(f'Valeurs manquantes dans {name} :\n{missing_percentage}\n')

check_missing_values(df,'data_intoxication')

# Symptômes manquants
df['symptomes'] = df['symptomes'].fillna('Non spécifié')

# Résultat analyse
df.loc[
    (df['analyse_laboratoire'] == 'Aucune analyse') &
    (df['resultat_analyse'].isna()),
    'resultat_analyse'
] = 'Non applicable'

# Mesures prises
df.loc[
    (df['inspection_effectuee'] == 'Non') &
    (df['mesures_prises'].isna()),
    'mesures_prises'
] = 'Non applicable'

# Hôpital
df.loc[
    (df['hospitalisation'] == 'Non') &
    (df['id_hopital'].isna()),
    'id_hopital'
    ]='N/A'

df.loc[
  (df['hospitalisation'] == 'Non') &
  (df['nom_hopital'].isna()),
  'nom_hopital'
    ] = 'Non hospitalisé'

# Cas incohérent : hospitalisé mais hôpital manquant
df.loc[
  (df['hospitalisation'] == 'Oui') &
  (df['id_hopital'].isna()),
  'id_hopital'
    ] = 'À vérifier'

df.loc[
  (df['hospitalisation'] == 'Oui') &
  (df['nom_hopital'].isna()),
  'nom_hopital'
  ] = 'À vérifier'

#NaN
df['id_hopital'] = df['id_hopital'].fillna('À vérifier')
df['nom_hopital'] = df['nom_hopital'].fillna('À vérifier')

check_missing_values(df, 'data_intoxication')

"""##Correction des espaces et casse"""

print(df.columns.tolist())

colonnes_texte = [
        'ville', 'region', 'nom_etablissement', 'type_etablissement',
        'lieu_consommation', 'type_aliment', 'aliment_suspect', 'categorie_aliment',
        'marque_aliment', 'source_alimentaire', 'symptome_principal', 'gravite',
        'hospitalisation', 'nom_hopital', 'traitement_administre', 'medicament_administre',
        'analyse_laboratoire', 'resultat_analyse', 'agent_pathogene_suspecte',
        'source_signalement', 'inspection_effectuee', 'resultat_inspection',
        'mesures_prises', 'fermeture_etablissement', 'symptomes'
    ]

cols_existantes = [c for c in colonnes_texte if c in df.columns]

df[cols_existantes] = (
  df[cols_existantes]
  .astype("string")
  .apply(lambda col: col.str.replace(r"\s+", " ", regex=True).str.strip())
    )

df['saison'] = df['saison'].astype(str).str.strip().str.capitalize()

# Nettoyage global
obj_cols = df.select_dtypes(include='object').columns
for col in obj_cols:
   df[col] = df[col].astype(str).str.strip()

# Harmonisation casse
df['ville'] = df['ville'].astype(str).str.title()
df['region'] = df['region'].astype(str).str.title()
df['gravite'] = df['gravite'].astype(str).str.capitalize()

# Oui / Non standardisation
mapping_oui_non = {
        'oui': 'Oui',
        'non': 'Non',
        'yes': 'Oui',
        'no': 'Non',
        'true': 'Oui',
        'false': 'Non'
    }

for col in ['hospitalisation', 'fermeture_etablissement', 'inspection_effectuee']:
        if col in df.columns:
            df[col] = df[col].astype(str).str.lower().map(mapping_oui_non).fillna(df[col])

# Genre
df['genre_patient'] = (
    df['genre_patient']
    .astype(str)
    .str.strip()
    .str.upper()
    .map({'F': 'Femme', 'M': 'Homme'})
    .fillna(df['genre_patient'])
    )

"""##Correction du type de données"""

df.info()

# Dates
colonnes_dates = [
    'date_cas',
    'date_achat',
    'date_consomation',
    'date_declaration'
    ]

for col in colonnes_dates:
    if col in df.columns:
        df[col] = pd.to_datetime(
            df[col],
            format='%Y-%m-%d',
            errors='coerce'
        )

# Heures
colonnes_heures = [
        'heure_cas',
        'heure_consomation'
    ]

for col in colonnes_heures:
      if col in df.columns:
          df[col] = pd.to_datetime(df[col], format='%H:%M', errors='coerce').dt.time

print(df['heure_cas'])

# Colonnes numériques
colonnes_int = [
        'age_patient',
        'nombre_personnes_exposees',
        'nombre_personnes_malades',
        'duree_symptomes_heures',
        'jour',
        'mois',
        'annee'
    ]

for col in colonnes_int:
     if col in df.columns:
         df[col] = pd.to_numeric(df[col], errors='coerce')

# Température
df['temperature_patient'] = pd.to_numeric(df['temperature_patient'], errors='coerce')

# Anomalie
df['anomalie'] = (
        df['anomalie']
        .astype(str)
        .str.strip()
        .str.upper()
        .map({'TRUE': True, 'FALSE': False})
    )

df.info()

print(df.head(3))

"""   ## Contrôle de cohérence des dates"""

# Supprimer uniquement les cas sans date principale
print(df['date_cas'].isna().sum())
df = df.dropna(subset=['date_cas'])

# Achat après consommation → invalider achat
df.loc[
  df['date_achat'] > df['date_consomation'],
        'date_achat'
  ] = pd.NaT

 # Consommation après apparition du cas → invalider consommation
df.loc[
  df['date_consomation'] > df['date_cas'],
        'date_consomation'
    ] = pd.NaT

# Déclaration avant apparition du cas → invalider déclaration
df.loc[
    df['date_cas'] > df['date_declaration'],
    'date_declaration'
    ] = pd.NaT

"""## Traitement des valeurs aberrantes"""

def check_outliers(df, name):
    numeric_columns = df.select_dtypes(include=['int64', 'float64']).columns
    results = {}

    for col in numeric_columns:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1

        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR

        nb_outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)].shape[0]
        results[col] = nb_outliers

    print(f'Outliers in {name}:\n{pd.Series(results)}\n')

check_outliers(df, "cas_intoxication")

# Âge
df.loc[
  (df['age_patient'] < 0) |
  (df['age_patient'] > 120),
  'age_patient'
    ] = pd.NA

#Temperature
df.loc[
  (df['temperature_patient'] < 35) |
  (df['temperature_patient'] > 42),
  'temperature_patient'
    ] = pd.NA

# Nombre exposés
df.loc[
  df['nombre_personnes_exposees'] <= 0,
  'nombre_personnes_exposees'
    ] = pd.NA

# Nombre malades
df.loc[
        (
          (df['nombre_personnes_malades'] < 0) |
            (
              df['nombre_personnes_malades']
                >
              df['nombre_personnes_exposees']
            )
        ),
        'nombre_personnes_malades'
    ] = pd.NA

# Durée symptômes
df.loc[
        (
          (df['duree_symptomes_heures'] < 0) |
          (df['duree_symptomes_heures'] > 336)
        ),
        'duree_symptomes_heures'
    ] = pd.NA

"""##Enrichissement des données"""

df['taux_attaque'] = (
        df['nombre_personnes_malades']
        .div(df['nombre_personnes_exposees'])
        .mul(100)
        .round(2)
    )

# Groupe d'âge
conditions = [
        df['age_patient'] <= 12,
        (df['age_patient'] >= 13) & (df['age_patient'] <= 17),
        (df['age_patient'] >= 18) & (df['age_patient'] <= 35),
        (df['age_patient'] >= 36) & (df['age_patient'] <= 59),
        df['age_patient'] >= 60
    ]

categories = [
        'Enfant',
        'Adolescent',
        'Jeune adulte',
        'Adulte',
        'Senior'
    ]

df['groupe_age'] = np.select(
        conditions,
        categories,
        default='Non renseigné'
    )



"""## Probleme ville et region"""

print(df.groupby('ville')['region'].agg(lambda x: x.mode()[0]))

mapping_correct = {
    'Antananarivo'  : 'Analamanga',
    'Antsirabe'     : 'Vakinankaratra',
    'Fianarantsoa'  : 'Haute Matsiatra',
    'Toamasina'     : 'Atsinanana',
    'Mahajanga'     : 'Boeny',
    'Toliara'       : 'Atsimo-Andrefana',
    'Antsiranana'   : 'Diana',
    'Morondava'     : 'Menabe',
    'Antalaha'      : 'Sava',
    'Maroantsetra'  : 'Analanjirofo',
    'Ambatondrazaka': 'Alaotra-Mangoro',
    'Manakara'      : 'Vatovavy'
}

nb_incorrectes = (df['region'] != df['ville'].map(mapping_correct)).sum()
print(f"Lignes avec région incorrecte : {nb_incorrectes}")

df['region'] = df['ville'].map(mapping_correct)

print(df.groupby('ville')['region'].agg(lambda x: x.mode()[0]))



print("\nTransformation terminée.")
    print(f"Nombre de lignes : {len(df)}")
    print(f"Nombre de colonnes : {len(df.columns)}")

    print("\nDates invalidées après contrôle :")
    print(f"date_achat : {df['date_achat'].isna().sum()}")
    print(f"date_consomation : {df['date_consomation'].isna().sum()}")
    print(f"date_declaration : {df['date_declaration'].isna().sum()}")

    print("\n===== RÉSUMÉ DE LA TRANSFORMATION =====")
    print(f"Lignes finales : {len(df)}")
    print(f"Colonnes finales : {len(df.columns)}")
    print(f"Âges invalides : {df['age_patient'].isna().sum()}")
    print(f"Températures invalides : {df['temperature_patient'].isna().sum()}")
    print(f"Dates d'achat invalides : {df['date_achat'].isna().sum()}")
    print(f"Dates de consommation invalides : {df['date_consomation'].isna().sum()}")
    print(f"Dates de déclaration invalides : {df['date_declaration'].isna().sum()}")